# Generated by Django 5.2.8 on 2025-11-22 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.pet'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='veterinarian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL),
        ),
    ]
